// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializeApp():Promise<void>;

export function LaunchGame(arg1:string,arg2:string,arg3:string):Promise<void>;
