// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializeApp() {
  return window['go']['main']['App']['InitializeApp']();
}

export function LaunchGame(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2, arg3);
}
